[package]
name = "placements-tree"
version = "0.1.0"
authors = ["Kirill Pavkin"]
description = "Tree of Placements"
readme = "README.md"
repository = "https://github.com/stavegan/placements-tree"
license = "MIT OR Apache-2.0"
edition = "2021"
